### ISSUE TITLE
1.4.1 版本 import 模块 验证 错误信息 add bug

### ISSUE THREAD

**Issue by biubiubiu3971** [open-hand/hzero#16]
org.hzero.boot.imported.domain.entity.ImportData.addErrorMsg
看内里逻辑，append错误信息，超出最大长度省掉最大长度后面的。现在的是用传入的错误信息判断最长字符串长度，应该是用append 后的错误信息

**Comment by partonstart** [comment]
![image](https://user-images.githubusercontent.com/12933368/125386010-2648b780-e3ce-11eb-9235-3259006fef82.png)
是会截取追加后的错误消息。

**Comment by biubiubiu3971** [comment]
使用错了吧，应该使用属性errormsg，用了入参

**Comment by biubiubiu3971** [comment]
> ![image](https://user-images.githubusercontent.com/12933368/125386010-2648b780-e3ce-11eb-9235-3259006fef82.png)
> 
> 是会截取追加后的错误消息。

应该用追加后的字符串，不应该用入参来判断

**Comment by biubiubiu3971** [comment]
关闭
