### ISSUE TITLE
请问1.5啥时候更新？

### ISSUE THREAD

**Issue by CrazyMelody** [open-hand/hzero#17]
感谢分享，终于找到一个平台级别的开源项目了，而不是那种烂大街的脚手架。

请问1.5啥时候能更新？

**Comment by partonstart** [comment]
计划2022年春节后，我们会发新商业版本1.9，同步会更新开源版1.5

**Comment by doucheng** [comment]
感觉项目组的开源。

**Comment by partonstart** [comment]
> 感觉项目组的开源。

刚发了1.9，正在筹备1.5开源
