### ISSUE TITLE
没找到对应实现，请问如何实现如下接口的？

### ISSUE THREAD

**Issue by GongLe** [open-hand/hzero#47]
查阅报表模块时，发现未能找到如下两个接口实现，请问是如何实现的？
`org.hzero.boot.report.app.IReportService.java`
`org.hzero.starter.report.domain.service.ITemplateReportService`

![Clip_2024-08-29_18-04-24](https://github.com/user-attachments/assets/96015c34-f6fc-409a-8554-048d9a3c9c30)

**Comment by neko-11** [comment]
org.hzero.boot.report.app.IReportService.java  是HZERO预留给开发人员可以实现自定义的报表文件的扩展方法，根据实际需要决定是否使用，以下是使用文档
# 自定义报表生成

## 1. 报表数据集定义

服务依赖本客户端后，会新增一个接口`/v1/report/execute`

数据集定义指定该接口

![image](https://github.com/user-attachments/assets/6bcc9e5b-0872-4fd9-a033-4c3acf6ebb66)


同时报表定义页面必须指定报表为异步


## 2. 报表生成实现

报表生成需要实现`org.hzero.boot.report.app.IReportService`接口，重写`execute`方法。同时类需要注入容器。

```java
/**
 * 示例任务
 */
@Component
public class Demo implements IReportService {

    @Override
    public ByteArrayOutputStream execute(Map<String, String> params) {
        // 生成报表文件
		...
        return data;
    }
}
```

报表文件的文件名默认为  `时间戳.xlsx`，若要自定义文件名可重写`filename`方法

**Comment by neko-11** [comment]
org.hzero.starter.report.domain.service.ITemplateReportService  是报表服务预留的模板报表实现，目前暂未使用，可不用关注

**Comment by GongLe** [comment]
感谢回复
![0186D22B](https://github.com/user-attachments/assets/accbd61d-90ca-4e79-b0d5-4a029a4d43f4)
