### ISSUE TITLE
前端运行后报500

### ISSUE THREAD

**Issue by minliacom** [open-hand/hzero#6]
看起来是由于 self接口报了 403 想通过 iam POST /v1/tool/permission/fresh 来刷新时又发现无法登录到swagger里面, 请大神指点一下, 谢谢!

PERMISSION_MISMATCHerror.permission.mismatchThis request mismatch any permission

![image](https://user-images.githubusercontent.com/10692860/94882699-4a6c8500-049b-11eb-84af-0bb4bcbd4f46.png)

**Comment by mm20140616** [comment]
采用的是哪种部署方式呢？可以重启下iam服务试试看。

**Comment by hsion** [comment]
我也出现了同样的问题。所有服务都起来了。
环境macos，单机启动所有服务
![image](https://user-images.githubusercontent.com/14086103/95545393-5b377080-0a30-11eb-969b-736c4235d5f0.png)

**Comment by mm20140616** [comment]
本地更新一下iam服务，之前加了一个类进去不知道你们有没有更新，更新后再启动iam服务试试。如果权限还是没刷进去，可以看看iam服务和admin服务有没有什么奇怪的日志可以发出来看看

**Comment by hsion** [comment]
更新了iam服务就ok了，谢谢
